name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: pnpm install

      - name: Build src code
        env:
          PRI_KEY: ${{ secrets.PRI_KEY }}
          PUB_KEY: ${{ secrets.PUB_KEY }}
        run: npm run build:publish

      - name: Get package info
        run: |
          node -p '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
          node -p '`PACKAGE_NAME=${require("./scripts/utils.js").buildPakageName()}`' >> $GITHUB_ENV
          node -p '`VERSION_NAME=${require("./scripts/constants.js").EXTENSION.versionInfoName}`' >> $GITHUB_ENV

      - name: Create git tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./publish/changeLog.md
          prerelease: false
          draft: false
          tag_name: v${{ env.PACKAGE_VERSION }}
          files: |
            ./build/${{ env.PACKAGE_NAME }}
            ./build/${{ env.VERSION_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate file MD5
        run: |
          md5sum ./build/*.alix
